### ISSUE TITLE
OINK-1349 | Migrate "userPhoneNumberSearch" Query

### ISSUE THREAD

**Issue by SilvioArzeno** [Alcancia-io/Alcancia-FrontEnd#220]
The **`userPhoneNumberSearch`** query is getting deprecated as of https://github.com/Alcancia-io/Alcancia-BackEnd/pull/142 and has to be migrated to **`searchUserByTelephoneNumber`** 

ClickUp Task: [OINK-1349](https://app.clickup.com/t/24497898/OINK-1349)

**Comment by bujosa** [comment]
Close the issue if is already resolve
